### ISSUE TITLE
Raw SQL support

### ISSUE THREAD

**Issue by Toilal** [rmpestano/dbunit-rules#14]
Would it be possible to add support of raw SQL script datasets ? It seems not to be supported by by DbUnit itself, but could be handy in some cases though.

**Comment by rmpestano** [comment]
Hi @Toilal, you can execute sql scripts before and after, it helps for your case?

see here https://github.com/rmpestano/dbunit-rules/blob/master/core/src/test/java/com/github/dbunit/rules/DBUnitRulesIt.java#L65

**Comment by rmpestano** [comment]
Currently we have only **executeStatementsBefore** but I think it would be useful to have scripts execution before tests where statements are separated by ';' inside a .sql script.

**Comment by rmpestano** [comment]
Hi again @Toilal,

It should be fixed now, you can use [this test](https://github.com/rmpestano/dbunit-rules/blob/master/core/src/test/java/com/github/dbunit/rules/ScriptsIt.java#L22) as reference.

Any problem just come back here, thanks for your feedback so far. 

PS: its available on [central snapshots](https://github.com/rmpestano/dbunit-rules#6-snapshots).
