### ISSUE TITLE
TestExtensionContext had been merged into ExtensionContext

### ISSUE THREAD

**Issue by realmfoo** [rmpestano/dbunit-rules#57]
Class `TestExtensionContext` had been merged into `ExtensionContext` in JUnit 5.0 M5, thus this plugin doesn't work now.

**Comment by rmpestano** [comment]
Hi @realmfoo, as stated in [readme](https://github.com/rmpestano/dbunit-rules#dbunit-rules-project-migrated-to-database-rider-organization) this plugin is not maintained anymore.
